An 4358 flow live query wrapper graph ql endpoint s
FlipsideCrypto/livequery-models pull request #82
Opened 2024-01-12 10:21 UTC by WHYTEWYLL

2024-01-18 17:31 UTC, juls858 requested changes
please rename the udf to something more descriptive
like allday.graph or allday.graphql

2024-01-18 17:31 UTC, juls858 commented on macros/marketplace/allday/udfs.yaml.sql
It looks like this route is only for GraphQL, it should be renamed.

2024-01-19 19:50 UTC, juls858 approved these changes

2024-01-23 20:03 UTC, WHYTEWYLL commented on macros/marketplace/allday/udfs.yaml.sql
> +    COMMENT = $$Run a graphql query on AllDay.$$
It doesnt exist

2024-01-24 17:03 UTC, juls858 approved these changes

2024-01-24 20:11 UTC, merged