add/udf_int_to_binary
FlipsideCrypto/livequery-models pull request #87
Opened 2024-02-27 20:57 UTC by mattromano

`dbt run -m models/deploy/core/utils.sql --vars '{"UPDATE_UDFS_AND_SPS":true, DROP_UDFS_AND_SPS: false}'`

2024-02-27 22:15 UTC, drethereum commented on macros/core/utils.yaml.sql
> +- name: {{ schema }}.udf_int_to_binary
this has the same name as the udf above, is that intentional? noticed they use different macros

2024-02-28 19:43 UTC, juls858 requested changes

2024-02-28 20:12 UTC, mattromano commented on macros/core/utils.yaml.sql
> +    - [num, INTEGER]
Updated this and test manually, it was handling ints and strings:
```
select ARBITRUM_DEV.UTILS.UDF_INT_TO_BINARY(123456789)
union all
select ARBITRUM_DEV.UTILS.UDF_INT_TO_BINARY('123456789');
```

Would out original tests check for the INT to STRING conversion. The first one uses a int to test and the big number uses a string to test:

```
      - name: udf_int_to_binary
        tests:
          - test_udf:
              name: test_utils__udf_int_to_binary
              args: 123456789
              assertions: 
              - result = '111010110111100110100010101'
      - name: udf_int_to_binary
        tests:
          - test_udf:
              name: test_utils__udf_int_to_binary_large_number
              args: "'123456789123456789123456789123456789123456789'"
              assertions: 
              - result = '101100010010011011011100101001111010001001110011010111111101111101010111011001001101000001111110001010100001011011010000100000001000101111100010101'
```

Or is there an additional test we would need to run?

2024-02-28 21:43 UTC, juls858 approved these changes

2024-02-28 21:47 UTC, merged